services:
  - type: web
    name: cineverse-api
    env: docker
    plan: free
    region: ohio
    branch: main
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
